// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sunrtkkyxfczttntdroz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1bnJ0a2t5eGZjenR0bnRkcm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTQ4OTIsImV4cCI6MjA2MDQ5MDg5Mn0.cU10d9-7RpsYPSTh0WPHnBC-rhRyXAu3Na6KWPWi0xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);